services:
  # --- BROKER SETOR 1 ---
  broker-app-1:
    build: ./broker
    container_name: broker-app-1
    hostname: broker1
    ports:
      - "1053:1053"
      - "8080:8080"
    networks:
      - pbl-net
    environment:
      - COMET_URL=node0:26657

  node0:
    image: cometbft/cometbft:v0.38.x
    container_name: node0
    hostname: node0
    ports:
      - "26657:26657"
    volumes:
      - ./minha-rede/node0:/cometbft
    command: node --proxy_app=tcp://broker-app-1:26658 --rpc.laddr=tcp://0.0.0.0:26657 --p2p.laddr=tcp://0.0.0.0:26656 --p2p.persistent_peers="05bae741b457ad946138ec071bc29a1eed8c3ddf@node0:26656,dd6a278b150e6287027d6597ed424f0b371b301f@node1:26656,04e4459859e8a0ed42327557eeb3d61613b048a4@node2:26656,94e47f538fb70bcdbfcc27e33718eb3448aa721a@node3:26656"
    depends_on:
      - broker-app-1
    networks:
      - pbl-net

  # --- BROKER SETOR 2 ---
  broker-app-2:
    build: ./broker
    container_name: broker-app-2
    hostname: broker2
    ports:
      - "1054:1053"
      - "8081:8080"
    networks:
      - pbl-net
    environment:
      - COMET_URL=node1:26657

  node1:
    image: cometbft/cometbft:v0.38.x
    container_name: node1
    hostname: node1
    ports:
      - "26660:26657"
    volumes:
      - ./minha-rede/node1:/cometbft
    command: node --proxy_app=tcp://broker-app-2:26658 --rpc.laddr=tcp://0.0.0.0:26657 --p2p.laddr=tcp://0.0.0.0:26656 --p2p.persistent_peers="05bae741b457ad946138ec071bc29a1eed8c3ddf@node0:26656,dd6a278b150e6287027d6597ed424f0b371b301f@node1:26656,04e4459859e8a0ed42327557eeb3d61613b048a4@node2:26656,94e47f538fb70bcdbfcc27e33718eb3448aa721a@node3:26656"
    depends_on:
      - broker-app-2
    networks:
      - pbl-net

  # --- BROKER SETOR 3 ---
  broker-app-3:
    build: ./broker
    container_name: broker-app-3
    hostname: broker3
    ports:
      - "1055:1053"
      - "8082:8080"
    networks:
      - pbl-net
    environment:
      - COMET_URL=node2:26657

  node2:
    image: cometbft/cometbft:v0.38.x
    container_name: node2
    hostname: node2
    ports:
      - "26663:26657"
    volumes:
      - ./minha-rede/node2:/cometbft
    command: node --proxy_app=tcp://broker-app-3:26658 --rpc.laddr=tcp://0.0.0.0:26657 --p2p.laddr=tcp://0.0.0.0:26656 --p2p.persistent_peers="05bae741b457ad946138ec071bc29a1eed8c3ddf@node0:26656,dd6a278b150e6287027d6597ed424f0b371b301f@node1:26656,04e4459859e8a0ed42327557eeb3d61613b048a4@node2:26656,94e47f538fb70bcdbfcc27e33718eb3448aa721a@node3:26656"
    depends_on:
      - broker-app-3
    networks:
      - pbl-net

  # --- BROKER SETOR 4 ---
  broker-app-4:
    build: ./broker
    container_name: broker-app-4
    hostname: broker4
    ports:
      - "1056:1053"
      - "8083:8080"
    networks:
      - pbl-net
    environment:
      - COMET_URL=node3:26657

  node3:
    image: cometbft/cometbft:v0.38.x
    container_name: node3
    hostname: node3
    ports:
      - "26666:26657"
    volumes:
      - ./minha-rede/node3:/cometbft
    command: node --proxy_app=tcp://broker-app-4:26658 --rpc.laddr=tcp://0.0.0.0:26657 --p2p.laddr=tcp://0.0.0.0:26656 --p2p.persistent_peers="05bae741b457ad946138ec071bc29a1eed8c3ddf@node0:26656,dd6a278b150e6287027d6597ed424f0b371b301f@node1:26656,04e4459859e8a0ed42327557eeb3d61613b048a4@node2:26656,94e47f538fb70bcdbfcc27e33718eb3448aa721a@node3:26656"
    depends_on:
      - broker-app-4
    networks:
      - pbl-net

  # --- DRONES ---
  drone-1:
    build: ./drone 
    container_name: drone1
    hostname: drone1
    environment:
      - BROKER_ADDR=broker-app-1:1053
      - BROKERS_ADDR=broker-app-2:1053,broker-app-3:1053,broker-app-4:1053
    networks:
      - pbl-net
    depends_on:
      - broker-app-1

  drone-2:
    build: ./drone 
    container_name: drone2
    hostname: drone2
    environment:
      - BROKER_ADDR=broker-app-2:1053
      - BROKERS_ADDR=broker-app-1:1053,broker-app-3:1053,broker-app-4:1053
    networks:
      - pbl-net
    depends_on:
      - broker-app-2

networks:
  pbl-net:
    driver: bridge